//Generated by Blueprint
using System;
using System.Collections.Generic;
namespace Blueprint.Logic
{
	[Serializable]
	public class AutoTest_ProcessStruct
	{
		public int ID;
		public string TriggerType;
		public List<string> TriggerValue;
		public int TodoType;
		public string TodoValue;
		public float TodoDelay;
		public int Next;
		public int OperationType;
		
	}
	
}