//Generated by Blueprint
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
namespace Blueprint.Logic
{
	public partial class Client
	{
		private static Dictionary<int, AutoTest_EventManagerConfigStruct> _AutoTest_EventManagerConfig = new Dictionary<int, AutoTest_EventManagerConfigStruct>()
		{
			[1] = new Blueprint.Logic.AutoTest_EventManagerConfigStruct()
			{
				ID = 1,
				TriggerType = "OpenUI",
				TriggerValue = new List<string>()
				{
					"Window/Guide/GuideObjectiveWindow",
					
				},
				TodoType = 2,
				TodoList = new List<string>()
				{
					"Window/Guide/GuideObjectiveWindow",
					
				},
				TodoDelay = 1.0f,
				LoopNum = 0,
				Next = 0,
				OperationType = 0,
				
			},
			
		};
		public static ReadOnlyDictionary<int, AutoTest_EventManagerConfigStruct> AutoTest_EventManagerConfig = new ReadOnlyDictionary<int, AutoTest_EventManagerConfigStruct>(_AutoTest_EventManagerConfig);
		
	}
	
}