//Generated by Blueprint
using System;
using System.Collections.Generic;
using UnityEngine;
namespace Blueprint.Logic
{
	public class AutoTest_ListenEvent : Blueprint.Logic.BP_Base
	{
		public AutoTest_ListenEvent()
		{
			
		}
		public override void Start()
		{
			//预定义节点OnMessage_2
			Blueprint.BpGlobalEvent.OnBpAction += CustomEvent;
			
		}
		public virtual void CustomEvent(string CustomEvent_3_param__0, List<string> CustomEvent_3_param__1)
		{
			//节点Greater_11
			var Greater_11_ret = CustomEvent_3_param__1.Count > 0;
			//预定义节点IfThenElse_9
			if (Greater_11_ret)
			{
				//节点StringValue_6
				var StringValue_6_value = " - ";
				//节点StringConcat_5
				var StringConcat_5_value = "AutoTest_ListenEvent: 触发事件 - " + CustomEvent_3_param__0 + StringValue_6_value + CustomEvent_3_param__1[0];
				//执行节点Log_4
				UnityEngine.Debug.Log(StringConcat_5_value);
				
			}
			else
			{
				//节点StringValue_14
				var StringValue_14_value = " -  None";
				//节点StringConcat_13
				var StringConcat_13_value = "AutoTest_ListenEvent: 触发事件 - " + CustomEvent_3_param__0 + StringValue_14_value;
				//执行节点Log_12
				UnityEngine.Debug.Log(StringConcat_13_value);
				
			}
			
		}
		
	}
}