//Generated by Blueprint
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
namespace Blueprint.Logic
{
	public partial class Client
	{
		private static Dictionary<int, AutoTest_ProcessStruct> _AutoTest_ProcessConfig = new Dictionary<int, AutoTest_ProcessStruct>()
		{
			[1] = new Blueprint.Logic.AutoTest_ProcessStruct()
			{
				ID = 1,
				TriggerType = "LoadingEnd",
				TriggerValue = new List<string>()
				{
					"3783757376",
					
				},
				TodoType = 3,
				TodoValue = "Lower/HallDlg_New/panel_bottom_right/btn_attack/image_btn",
				TodoDelay = 5.0f,
				Next = 0,
				OperationType = 1,
				
			},
			[2] = new Blueprint.Logic.AutoTest_ProcessStruct()
			{
				ID = 2,
				TriggerType = "Call",
				TriggerValue = new List<string>()
				{
					"None",
					
				},
				TodoType = 3,
				TodoValue = "Middle/BattleSkillView/SkillButtons/Basic/A",
				TodoDelay = 2.0f,
				Next = 0,
				OperationType = 1,
				
			},
			[3] = new Blueprint.Logic.AutoTest_ProcessStruct()
			{
				ID = 3,
				TriggerType = "TalkStart",
				TriggerValue = new List<string>()
				{
					"Orignal_Drama_A01_01_02",
					
				},
				TodoType = 3,
				TodoValue = "Canvas/CutsceneDialog(Clone)/DialogCutscene/panel_icon_click/Next",
				TodoDelay = 1.0f,
				Next = 0,
				OperationType = 1,
				
			},
			[4] = new Blueprint.Logic.AutoTest_ProcessStruct()
			{
				ID = 4,
				TriggerType = "TalkStart",
				TriggerValue = new List<string>()
				{
					"Orignal_Drama_A01_01_02_1",
					
				},
				TodoType = 3,
				TodoValue = "Canvas/CutsceneDialog(Clone)/DialogCutscene/panel_icon_click/Next",
				TodoDelay = 1.0f,
				Next = 8,
				OperationType = 1,
				
			},
			
		};
		public static ReadOnlyDictionary<int, AutoTest_ProcessStruct> AutoTest_ProcessConfig = new ReadOnlyDictionary<int, AutoTest_ProcessStruct>(_AutoTest_ProcessConfig);
		
	}
	
}