//Generated by Blueprint
using System;
using System.Collections.Generic;
using UnityEngine;
namespace Blueprint.Logic
{
	public class AutoTest_InitTest : Blueprint.Logic.BP_Base
	{
		public AutoTest_InitTest()
		{
			
		}
		public override void Start()
		{
			//执行节点StartProfiler_10
			PTestNode.StartProfiler("Test");
			//执行节点CaseSteps_7
			PTestNode.CaseSteps("初始化测试", "Autotest开启", "初始化测试", true, ScreenType.SceenShot);
			//预定义节点Delay_4
			DelayControl.Instance.Delay(this,"_03FC851F-45EE-4529-8011-76B99E45D8B3_4",()=>{
				try {
					//执行节点CaseSteps_8
					PTestNode.CaseSteps("初始化测试", "Autotest结束", "初始化测试", true, ScreenType.SceenShot);
					//执行节点StopProfiler_11
					PTestNode.StopProfiler();
					//执行节点CaseFinished_9
					PTestNode.CaseFinished();
					
				} catch (Exception e){
					Debug.LogError("AutoTest_InitTest.class  " + "NewGraph  ,nodeId:" + "4" + "\n" + e.ToString());
				}
			},10.0f);
			
		}
		
	}
}