//Generated by Blueprint
using System;
using System.Collections.Generic;
namespace Blueprint.Logic
{
	public partial class Client
	{
		public static Blueprint.Logic.AutoTest_ProcessCase AutoTest_ProcessCaseInstance = default;


}

}