//Generated by Blueprint
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
namespace Blueprint.Logic
{
	public partial class Client
	{
		private static Dictionary<string, PlanSetupStruct> _PlanSetupConfig = new Dictionary<string, PlanSetupStruct>()
		{
			["1"] = new Blueprint.Logic.PlanSetupStruct()
			{
				ID = "1",
				IP = "https://trident.oa.wanmei.net/public/api ",
				ServerID = "10",
				WaitForButton = 600,
				WaitForWalk = 600,
				UserName = new List<string>()
				{
					"4000",
					"4001",
					
				},
				PassWord = "333",
				VersionID = "W4IA7kknblTsIv1mRtmj8TnvllRWmuJv",
				
			},
			
		};
		public static ReadOnlyDictionary<string, PlanSetupStruct> PlanSetupConfig = new ReadOnlyDictionary<string, PlanSetupStruct>(_PlanSetupConfig);
		
	}
	
}