//Generated by Blueprint
using System;
using System.Collections.Generic;
namespace Blueprint.Logic
{
	[Serializable]
	public class PlanSetupStruct
	{
		public string ID;
		public string IP;
		public string ServerID;
		public int WaitForButton;
		public int WaitForWalk;
		public List<string> UserName;
		public string PassWord;
		public string VersionID;
		
	}
	
}