//Generated by Blueprint
#pragma warning disable CS0414
using System;
using System.Collections.Generic;
using UnityEngine;
using Blueprint;
using Blueprint.Actor;
using Blueprint.UnityLogic;
[OrignBPClass("AT_EventManager")]
public class AT_EventManager_Field : ActorFieldBase
{
	private Dictionary<int, Blueprint.Logic.AutoTest_EventManagerConfigStruct> AutoTest_EventManagerData = new Dictionary<int, Blueprint.Logic.AutoTest_EventManagerConfigStruct>()
	{
		
	};
	private string TriggerType = "";
	private List<string> TriggerValue = new List<string>()
	{
		
	};
	private Blueprint.DelayHandle DelayHandle = default;
	private List<string> ToDoList = new List<string>()
	{
		
	};
	private Blueprint.Actor.ActorInvoke DoTypeOneInvoke = default;
	private int NextEventID = 0;
	private Blueprint.Actor.ActorInvoke DoTypeTwoInvoke = default;
	private int CurrEventID = 0;
	private int WalkToEventID = 0;
	public virtual void SetEventData(string SetEventData_url)
	{
		(actor as Blueprint.UnityLogic.AT_EventManager).SetEventData(SetEventData_url);
		
	}
	public virtual int GetEventID()
	{
		return (actor as Blueprint.UnityLogic.AT_EventManager).GetEventID();
		
	}
	public virtual void DoTypeOne()
	{
		(actor as Blueprint.UnityLogic.AT_EventManager).DoTypeOne();
		
	}
	public virtual void DoTypeTwo()
	{
		(actor as Blueprint.UnityLogic.AT_EventManager).DoTypeTwo();
		
	}
	public virtual void SetWalkToID(AnimationEvent animationEvent)
	{
		string SetWalkToID_gm = animationEvent.stringParameter;
		int SetWalkToID_ID = animationEvent.intParameter;
		(actor as Blueprint.UnityLogic.AT_EventManager).SetWalkToID(SetWalkToID_gm, SetWalkToID_ID);
		
	}
	public virtual void DoDiffOperation(AnimationEvent animationEvent)
	{
		int DoDiffOperation_operation = animationEvent.intParameter;
		string DoDiffOperation_cmd = animationEvent.stringParameter;
		(actor as Blueprint.UnityLogic.AT_EventManager).DoDiffOperation(DoDiffOperation_operation, DoDiffOperation_cmd);
		
	}
	
}