//Generated by Blueprint
#pragma warning disable CS0414
using System;
using System.Collections.Generic;
using UnityEngine;
using Blueprint;
using Blueprint.Actor;
using Blueprint.UnityLogic;
[OrignBPClass("AT_ProcessCase")]
public class AT_ProcessCase_Field : ActorFieldBase
{
	private Dictionary<int, Blueprint.Logic.AutoTest_ProcessStruct> AutoTest_ProcessData = new Dictionary<int, Blueprint.Logic.AutoTest_ProcessStruct>()
	{
		
	};
	private string TriggerType = "";
	private List<string> TriggerValue = new List<string>()
	{
		
	};
	private Blueprint.UnityLogic.AT_EventManager AT_Manager = default;
	private int WalkToEventID = 0;
	private Blueprint.DelayHandle DelayHandle = default;
	private int NextEventID = 0;
	private int CurrEventID = 0;
	private List<string> ToDoList = new List<string>()
	{
		
	};
	private Blueprint.Actor.ActorInvoke DoTypeOneInvoke = default;
	private Blueprint.Actor.ActorInvoke DoTypeTwoInvoke = default;
	private string RandomAccount = "";
	private int NewVar = 3;
	public virtual int GetEventID()
	{
		return (actor as Blueprint.UnityLogic.AT_ProcessCase).GetEventID();
		
	}
	public virtual void SetWalkToID(AnimationEvent animationEvent)
	{
		string SetWalkToID_gm = animationEvent.stringParameter;
		int SetWalkToID_ID = animationEvent.intParameter;
		(actor as Blueprint.UnityLogic.AT_ProcessCase).SetWalkToID(SetWalkToID_gm, SetWalkToID_ID);
		
	}
	public virtual void DoTypeOne()
	{
		(actor as Blueprint.UnityLogic.AT_ProcessCase).DoTypeOne();
		
	}
	public virtual void DoTypeTwo()
	{
		(actor as Blueprint.UnityLogic.AT_ProcessCase).DoTypeTwo();
		
	}
	public virtual void DoDiffOperation(AnimationEvent animationEvent)
	{
		int DoDiffOperation_operation = animationEvent.intParameter;
		string DoDiffOperation_cmd = animationEvent.stringParameter;
		(actor as Blueprint.UnityLogic.AT_ProcessCase).DoDiffOperation(DoDiffOperation_operation, DoDiffOperation_cmd);
		
	}
	
}