//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EditorEcs {

public enum XHitType {
  Back = 0,
  HeavyBack,
  FlyStart,
  FlyEnd,
  FlyAwayStart,
  FlyAwayEnd,
  Land,
  DownToIdle,
  YiShan,
  None,
  Max
}

}
