//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EditorEcs {

public enum XHitSlot {
  Normal_Slot = 0,
  Hit_1_Slot,
  Hit_2_Slot,
  Hit_3_Slot,
  Hit_4_Slot,
  Hit_5_Slot,
  Hit_6_Slot,
  Hit_7_Slot,
  Hit_8_Slot,
  Hit_9_Slot,
  Death_Slot,
  Tie_Slot,
  Charm_Slot,
  Paralysis_Slot,
  Frozen_Slot,
  Petrify_Slot,
  Max
}

}
