//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EditorEcs {

public enum XInputSlot {
  Normal_Slot = 0,
  Dash_Slot,
  Skill_1_Slot,
  Skill_2_Slot,
  Skill_3_Slot,
  Skill_4_Slot,
  Dash_Virtual_Slot,
  Skill_6_Slot,
  Skill_7_Slot,
  Normal_Virtual_Slot,
  Max
}

}
