//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EditorEcs {

public class XNet : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XNet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XNet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XNet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Xuthus_VirtualServerPINVOKE.delete_XNet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint sync_sequence {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_sync_sequence_set(swigCPtr, value);
    } 
    get {
      uint ret = Xuthus_VirtualServerPINVOKE.XNet_sync_sequence_get(swigCPtr);
      return ret;
    } 
  }

  public uint old_sequence {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_old_sequence_set(swigCPtr, value);
    } 
    get {
      uint ret = Xuthus_VirtualServerPINVOKE.XNet_old_sequence_get(swigCPtr);
      return ret;
    } 
  }

  public float interpolation {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_interpolation_set(swigCPtr, value);
    } 
    get {
      float ret = Xuthus_VirtualServerPINVOKE.XNet_interpolation_get(swigCPtr);
      return ret;
    } 
  }

  public XStateType state {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_state_set(swigCPtr, (int)value);
    } 
    get {
      XStateType ret = (XStateType)Xuthus_VirtualServerPINVOKE.XNet_state_get(swigCPtr);
      return ret;
    } 
  }

  public float action_ratio {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_action_ratio_set(swigCPtr, value);
    } 
    get {
      float ret = Xuthus_VirtualServerPINVOKE.XNet_action_ratio_get(swigCPtr);
      return ret;
    } 
  }

  public float face {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_face_set(swigCPtr, value);
    } 
    get {
      float ret = Xuthus_VirtualServerPINVOKE.XNet_face_get(swigCPtr);
      return ret;
    } 
  }

  public float x {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_x_set(swigCPtr, value);
    } 
    get {
      float ret = Xuthus_VirtualServerPINVOKE.XNet_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_y_set(swigCPtr, value);
    } 
    get {
      float ret = Xuthus_VirtualServerPINVOKE.XNet_y_get(swigCPtr);
      return ret;
    } 
  }

  public float z {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_z_set(swigCPtr, value);
    } 
    get {
      float ret = Xuthus_VirtualServerPINVOKE.XNet_z_get(swigCPtr);
      return ret;
    } 
  }

  public float velocity {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_velocity_set(swigCPtr, value);
    } 
    get {
      float ret = Xuthus_VirtualServerPINVOKE.XNet_velocity_get(swigCPtr);
      return ret;
    } 
  }

  public uint passive {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_passive_set(swigCPtr, value);
    } 
    get {
      uint ret = Xuthus_VirtualServerPINVOKE.XNet_passive_get(swigCPtr);
      return ret;
    } 
  }

  public uint condition_seq {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_condition_seq_set(swigCPtr, value);
    } 
    get {
      uint ret = Xuthus_VirtualServerPINVOKE.XNet_condition_seq_get(swigCPtr);
      return ret;
    } 
  }

  public uint switch_seq {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_switch_seq_set(swigCPtr, value);
    } 
    get {
      uint ret = Xuthus_VirtualServerPINVOKE.XNet_switch_seq_get(swigCPtr);
      return ret;
    } 
  }

  public uint while_seq {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_while_seq_set(swigCPtr, value);
    } 
    get {
      uint ret = Xuthus_VirtualServerPINVOKE.XNet_while_seq_get(swigCPtr);
      return ret;
    } 
  }

  public float percentage {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_percentage_set(swigCPtr, value);
    } 
    get {
      float ret = Xuthus_VirtualServerPINVOKE.XNet_percentage_get(swigCPtr);
      return ret;
    } 
  }

  public uint script_id {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_script_id_set(swigCPtr, value);
    } 
    get {
      uint ret = Xuthus_VirtualServerPINVOKE.XNet_script_id_get(swigCPtr);
      return ret;
    } 
  }

  public int script_version {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_script_version_set(swigCPtr, value);
    } 
    get {
      int ret = Xuthus_VirtualServerPINVOKE.XNet_script_version_get(swigCPtr);
      return ret;
    } 
  }

  public ulong skill_code {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_skill_code_set(swigCPtr, value);
    } 
    get {
      ulong ret = Xuthus_VirtualServerPINVOKE.XNet_skill_code_get(swigCPtr);
      return ret;
    } 
  }

  public ulong target {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_target_set(swigCPtr, value);
    } 
    get {
      ulong ret = Xuthus_VirtualServerPINVOKE.XNet_target_get(swigCPtr);
      return ret;
    } 
  }

  public ulong from_entt {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_from_entt_set(swigCPtr, value);
    } 
    get {
      ulong ret = Xuthus_VirtualServerPINVOKE.XNet_from_entt_get(swigCPtr);
      return ret;
    } 
  }

  public uint from_hash {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_from_hash_set(swigCPtr, value);
    } 
    get {
      uint ret = Xuthus_VirtualServerPINVOKE.XNet_from_hash_get(swigCPtr);
      return ret;
    } 
  }

  public int from_index {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_from_index_set(swigCPtr, value);
    } 
    get {
      int ret = Xuthus_VirtualServerPINVOKE.XNet_from_index_get(swigCPtr);
      return ret;
    } 
  }

  public float from_dir {
    set {
      Xuthus_VirtualServerPINVOKE.XNet_from_dir_set(swigCPtr, value);
    } 
    get {
      float ret = Xuthus_VirtualServerPINVOKE.XNet_from_dir_get(swigCPtr);
      return ret;
    } 
  }

  public XNet() : this(Xuthus_VirtualServerPINVOKE.new_XNet(), true) {
  }

}

}
