//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EditorEcs {

public enum XSpecialActionType {
  XSkybox = 0,
  XCriticalAttack,
  XUIState,
  XAimMode,
  XItemDrop,
  XItemPick,
  XSpaceTimeLock,
  XTriggerQteEvent,
  XCollisionType,
  XSpaceTimeLockEffect,
  XPlayCameraCurve,
  XSkillAttackField,
  XSceneEffect,
  XCinemachineControl,
  XDynamicBone,
  XClientFeature,
  XHitSlotFromHeader,
  Max
}

}
