//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EditorEcs {

public enum XStateType {
  Idle = 0,
  Move,
  Hit,
  Skill,
  Death,
  Max
}

}
