//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EditorEcs {

public enum XTargetSelectFilter {
  Defalut = 0,
  Farthest,
  Nearest,
  Hp_Highest,
  HP_Lowest,
  Hate_Highest,
  Random,
  Max
}

}
